# -*- coding: utf-8 -*-

## VALORES FIXOS

_CV={'V1': '84.0', 'V2': '90.0', 'V3': '80.0', 'V4': '70.0', 'V5': '93.0', 'V6': '100.0', 'V7': '93.0', 'V8': '100.0'}

_V={'V1': '4.0', 'V2': '4.4', 'V3': '3.6', 'V4': '3.2', 'V5': '4.0', 'V6': '4.4', 'V7': '4.0', 'V8': '4.4'}

## ROTAS

_TERCA=["GIBA'S", 'LOCATELLI', 'SARA', 'LORI', 'TRENZINHO', 'VERDES CAMPOS', 'ACADEMIA', 'ADEMIR', 'NOVO PAN', 'PASSARINHO', 'JÚLIO', 'ALICE', 'POSTAÇO', 'ESCOLINHA', 'SAPIRANGA', 'MARLI', 'PAULO PILATTI', 'VÓ MIRIAM', 'MIRIAM', 'BAUM', 'FEEVALE', 'TAILOR', 'FÁBIO', 'CERRO LARGO', 'DEISE', 'REMI', 'COSTANEIRA', 'GILMAR', 'IMPERIAL', 'WANDA', 'LILI', 'SCHUTZ', 'SUPER BEM', 'EVANDRO', 'REGINA', 'VÓ', 'NONOAI', 'CLÁUDIO']
_QUARTA=['ELIAS', 'DÉLCIO', 'SIMONE', 'SAMUEL', 'MARLI', 'CÉZAR', 'BOLACHA', 'JUVENTINO', 'ZENOILDE', 'MÔNICA', 'IRACI', 'LAMB', 'LOURDES', 'SERRINHA', 'GIBA', 'PEDRO', 'MARIA', 'DANIEL', 'CLÁUDIO', 'ANDRÉ', 'CARLOS', 'AURÉLIO', 'OBA OBA', 'JÚNIOR', 'PENNA', 'DOG\'S', 'TIA', 'APARECIDA', 'ANTÔNIO/BETTE', 'ANTÔNIO TORRE', 'PRIMUS', 'JAIR', 'FREEWAY', 'PAULO', 'TIA GETNET', 'VÔ GETNET', 'BOKAS', 'PAULO ROSA']
_QUINTA=['RICCI', 'JOEL', 'DAIANE', 'PARANÁ', 'JULIANO', 'MARLI', 'ANTÔNIO', 'ZÉ', 'ALEXANDRE', 'FLORES', 'JÔ', 'ALCEMAR', 'ALEMÃO', 'JÚLIO']

## ENTRADA

_C={}
_W=None

## CARGA

_CARGA={'BRT1': 0.0, 'VRT1': 0.0, 'BRT2': 0.0, 'BRT3': 0.0, 'BRDZ': 0.0, 'VRDZ': 0.0, 'BRMD': 0.0, 'VRMD': 0.0}

## HISTORICO

_H=[]
