# -*- coding: utf-8 -*-

## VALORES FIXOS

_box_price={'VRDZ': 100.0, 'BRMD': 93.0, 'BRDZ': 93.0, 'VRMD': 100.0, 'VRT1': 90.0, 'BRT1': 84.0, 'BRT2': 80.0, 'BRT3': 70.0}

_dozen_price={'BRT1': 4.0, 'VRT1': 4.4, 'BRT2': 3.6, 'BRT3': 3.2, 'BRDZ': 4.0, 'VRDZ': 4.4, 'BRMD': 4.0, 'VRMD': 4.4}

_font_size=15

## ROTAS

_tuesday=["GIBA'S", 'LOCATELLI', 'SARA', 'LORI', 'TRENZINHO', 'VERDES CAMPOS', 'ACADEMIA', 'ADEMIR', 'NOVO PAN', 'PASSARINHO', 'JULIO', 'ALICE', 'POSTACO', 'ESCOLINHA', 'SAPIRANGA', 'MARLI', 'PAULO PILATTI', 'VO MIRIAM', 'MIRIAM', 'BAUM', 'FEEVALE', 'TAILOR', 'FABIO', 'CERRO LARGO', 'DEISE', 'REMI', 'CAFE PELOTAS', 'GILMAR', 'IMPERIAL', 'WANDA', 'LILI', 'SCHUTZ', 'SUPER BEM', 'EVANDRO', 'REGINA', 'VO', 'NONOAI', 'CLAUDIO']
_wednesday=['ELIAS', 'DELCIO', 'SIMONE', 'SAMUEL', 'MARLI', 'CEZAR', 'BOLACHA', 'JUVENTINO', 'ZENOILDE', 'MONICA', 'IRACI', 'LAMB', 'LOURDES', 'SERRINHA', 'GIBA', 'PEDRO', 'MARIA', 'DANIEL', 'CLAUDIO', 'ANDRE', 'CARLOS', 'AURELIO', 'OBA OBA', 'JUNIOR', 'PENNA', "DOG'S", 'TIA', 'APARECIDA', 'ANTONIO/BETTE', 'ANTONIO TORRE', 'PRIMUS', 'JAIR', 'FREEWAY', 'PAULO', 'TIA GETNET', 'VO GETNET', 'BOKAS', 'PAULO ROSA']
_thursday=['RICCI', 'JOEL', 'DAIANE', 'TUA TERRA', 'PARANA', 'JULIANO', 'MARLI', 'ZE', 'ALEXANDRE', 'FLORES', 'JO', 'ALCEMAR', 'ALEMAO', 'JULIO']

## ENTRADA

_current_day=None
_current_route=[]

## CARGA

_load={'VRDZ': 0.0, 'BRMD': 0.0, 'BRDZ': 0.0, 'VRMD': 0.0, 'VRT1': 0.0, 'BRT1': 0.0, 'BRT2': 0.0, 'BRT3': 0.0}

## HISTORICO

_reported_list=[]
